---
- hosts: all
  become: true
  tasks: 
  
  - name: install apache2 package, install support for php, update package index
    ansible.builtin.package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

