---
- hosts: all
  become: true
  tags: always
  pre_tasks:


  - name: run pre_tasks
    ansible.builtin.apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"



- hosts: web_servers
  tags: ubuntu
  become: true
  tasks:


  - name: install apache2 and php support
    ansible.builtin.apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest

